### PR TITLE
Add hook to check for fuzzy messages

### LINKED ISSUE #18: Add hook to check fuzzy messages

### PR DESCRIPTION
**Pull request by mondeja**
Closes #18

### CODE REVIEW

**Comment by intiocean** [comment]
It would be great if the `fuzzy-messages` hook didn't warn about the metadata which is a fuzzy message itself.

**Comment by mondeja** [comment]
Why it should not warn about the metadata? It is just another `msgstr`.

**Comment by intiocean** [comment]
It's true that it's just another `msgstr` but it is my understanding that the metadata will always be `fuzzy`.

I have just had a look in the [docs](https://www.gnu.org/software/gettext/manual/gettext.html#PO-Files:~:text=An%20empty%20untranslated%2Dstring%20is%20reserved%20to%20contain%20the%20header%20entry%20with%20the%20meta%20information%20(see%20Header%20Entry).%20This%20header%20entry%20should%20be%20the%20first%20entry%20of%20the%20file.%20The%20empty%20untranslated%2Dstring%20is%20reserved%20for%20this%20purpose%20and%20must%20not%20be%20used%20anywhere%20else.) and it doesn't actually mention it being fuzzy though so maybe that isn't necessary?

**Comment by mondeja** [comment]
> but it is my understanding that the metadata will always be `fuzzy`.

Nope, it would be fuzzy if requires further review.

> I have just had a look in the [docs](https://www.gnu.org/software/gettext/manual/gettext.html#PO-Files:~:text=An%20empty%20untranslated%2Dstring%20is%20reserved%20to%20contain%20the%20header%20entry%20with%20the%20meta%20information%20(see%20Header%20Entry).%20This%20header%20entry%20should%20be%20the%20first%20entry%20of%20the%20file.%20The%20empty%20untranslated%2Dstring%20is%20reserved%20for%20this%20purpose%20and%20must%20not%20be%20used%20anywhere%20else.) and it doesn't actually mention it being fuzzy though so maybe that isn't necessary?

That's it, the documentation specifies that _"All comments, of either kind, are optional."_

**Comment by intiocean** [comment]
Acknowledged - Thanks! :)

**Pull request merged**
